### PR TITLE
docs(contributors) add contributor terrystrachan

### PR DESCRIPTION
**Pull request by terrystrachan**
## What:

Adding contributor terrystrachan

Issue number: N/A

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hmm, running `npm run contributors:generate` should have added new contributor also to the `about.component.html` template ?

**Comment by timdeschryver** [comment]
It could be I added the wrong command, in the PR template it's defined as `npm run contributors:add`.

**Comment by tomastrajan** [comment]
@timdeschryver both commands are important, first do `npm run contributors:add -- <contributor-name> <comma-separated-contributor-contributions>` and the run `npm run contributors:generate`

**Comment by terrystrachan** [comment]
apologies - i didnt run `npm run contributors:generate`

**Comment by timdeschryver** [comment]
Got it, this is all my fault then 😅 
I'll update the PR template and will also add a default issue template.

**Pull request merged**
