### PR TITLE
test(BigInputComponent): created unit test for BigInputComponent

### LINKED ISSUE #271: Create unit tests for big input component
Create unit test for `big-input.component.ts` in `big-input.component.spec.ts` that covers its functionality.

Please follow testing pattern introduced in [big-input-action.component.spec.ts](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/src/app/shared/big-input/big-input-action.component.spec.ts) or please suggest improvements in the comments.

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

### PR DESCRIPTION
**Pull request by hhubik**
fixes #271

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hi @hhubik ! Thank you for the adjusted PR. I will merge it.

For the future, I described git rebase with squashing in the comment of the previous PR so feel free to check and try it. Also for the  next time, please put `fixes #<issue-number>`in the commit message itself so that GitHub automatically connects and closes relevant issue.

Thank you again!

**Comment by tomastrajan** [comment]
@hhubik also one more thing the scope in the commit. For the future let's keep it on the module level. So it would have been `test(shared) ...`. 

In bigger apps there might be many components so to signify impact on other developers it makes sense to specify changed module which they should be aware of while they probably  don't know every single component location by heart.

**Comment by hhubik** [comment]
Hi @tomastrajan - glad to help.  Thank you for the learning opportunity :)

Regarding `fixes #<issue-number>`, I did put that in the `body` of the commit comment on a separate line.  I thought that is where it should go.  I now see that the examples in the latest `CONTRIBUTING` doc have it on the `subject` line, separated by a comma from the rest of the subject text.  Are you saying that having it in the body does not work and that it must be in the subject line?

If I read [this](https://help.github.com/articles/closing-issues-using-keywords/) correctly, it should work anywhere in the commit message.

Regarding `test(shared) ...` and module level, that sounds reasonable.  However, the `CONTRIBUTING` doc includes an example of a commit comment starting with `test(todos) ...`, where `todos` is a component, not a module.  If you want to use the module names for test scope, the doc should be updated to reflect that.

**Comment by tomastrajan** [comment]
Hi @hhubik !

Thank you for clarifications! I missed the fact that you provided fixes string in the commit body, of course that's enough, well done!

As for module level, you are right, I should adjust the documentation. In case of `todos` it was meant as a "submodule" of `examples` module even though it was not separated (extracted) yet. Todos contains component, reducer and effects. I agree that it is not obvious and docs can and will be improved.

Thank you for your feedback!

**Comment by tomastrajan** [comment]
@hhubik I have just updated [CONTRIBUTING.md](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) with more detailed info about commit scopes.

**Pull request merged**
