### PR TITLE
Changed changeDetection to OnPush

### PR DESCRIPTION
**Pull request by hhubik**
... for 
- BigInputComponent
- BigInputActionComponent

Also changed `SharedModule` import path.  The old one was  not working in my IDE (VS Code on Windows).

### CODE REVIEW

**Comment by tomastrajan** [comment]
Thank you very much for your effort! There are couple of issues still...

* failed build seems to be only caused by prettier check so you can try running `npm run prettier` locally to make the fix (also you try running `npm run ci` locally to try CI build if everything works out)

* also there seems to be merge conflicts ? maybe you can squash all commits in your branch into one and rebase on top of master

* please use `standard-version` commit message formatting as explained in [CONTRIBUTING.md](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) file
so in this case we would end up with `feat(shared): use OnPush change detection strategy` or something similar...

**Comment by tomastrajan** [comment]
Also the import should work because of the `path` property in main `tsconfig.json` file with aliases and `index.ts` barrel in shard module. Could VS code settings be adjust to recognize that configuration? I work mostly with Intellij IDEA where it causes no issues or warnings.

**Comment by hhubik** [comment]
I will try to address the issues tomorrow.  I get the same problem when running `npm run ci` locally.  Not sure what to do about that.  I wonder if it has something to do with my using Windows (8.1 x64).  Here is the log.  Any suggestions would be appreciated:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prettier:ci' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prettier:ci' ]
5 info lifecycle angular-ngrx-material-starter@6.0.0-rc.1~prettier:ci: angular-ngrx-material-starter@6.0.0-rc.1
6 verbose lifecycle angular-ngrx-material-starter@6.0.0-rc.1~prettier:ci: unsafe-perm in lifecycle true
7 verbose lifecycle angular-ngrx-material-starter@6.0.0-rc.1~prettier:ci: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Users\<user_a>\Documents\Angular2Dev\angular-ngrx-material-starter\node_modules\.bin;D:\Users\<user_a>\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;D:\Users\<user_a>\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Emulator Manager\1.0;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files\dotnet;C:\Program Files (x86)\GnuPG\bin;C:\Program Files\nodejs;D:\Users\<user_a>\.dnx\bin;D:\Users\<user_a>\AppData\Roaming\npm;D:\Users\<user_a>\AppData\Local\Programs\Fiddler;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl;C:\Program Files\Microsoft VS Code;D:\Users\<user_a>\AppData\Roaming\npm
8 verbose lifecycle angular-ngrx-material-starter@6.0.0-rc.1~prettier:ci: CWD: D:\Users\<user_a>\Documents\Angular2Dev\angular-ngrx-material-starter
9 silly lifecycle angular-ngrx-material-starter@6.0.0-rc.1~prettier:ci: Args: [ '/d /s /c',
9 silly lifecycle   'prettier {src,e2e}/**/*.{ts,json,md,scss} --list-different' ]
10 silly lifecycle angular-ngrx-material-starter@6.0.0-rc.1~prettier:ci: Returned: code: 1  signal: null
11 info lifecycle angular-ngrx-material-starter@6.0.0-rc.1~prettier:ci: Failed to exec prettier:ci script
12 verbose stack Error: angular-ngrx-material-starter@6.0.0-rc.1 prettier:ci: `prettier {src,e2e}/**/*.{ts,json,md,scss} --list-different`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at EventEmitter.emit (events.js:214:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid angular-ngrx-material-starter@6.0.0-rc.1
14 verbose cwd D:\Users\<user_a>\Documents\Angular2Dev\angular-ngrx-material-starter
15 verbose Windows_NT 6.3.9600
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prettier:ci"
17 verbose node v8.10.0
18 verbose npm  v5.6.0
19 error code ELIFECYCLE
20 error errno 1
21 error angular-ngrx-material-starter@6.0.0-rc.1 prettier:ci: `prettier {src,e2e}/**/*.{ts,json,md,scss} --list-different`
21 error Exit status 1
22 error Failed at the angular-ngrx-material-starter@6.0.0-rc.1 prettier:ci script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

**Comment by hhubik** [comment]
@tomastrajan I have looked into the issue with module resolution in VS Code.  I have found a workaround/solution [here](https://github.com/Microsoft/vscode/issues/42095) that consists of changing 
`"baseUrl": "./"`
to
`"baseUrl": "src"`

in `tsconfig.json`

I tried that. The app compiles and runs.  Do you want me to include it in my other changes?

**Comment by tomastrajan** [comment]
Gonna try it locally first and will let you know soon.

**Comment by tomastrajan** [comment]
Also, as for the error when running `npm run ci`, it could be caused by using windows cmd... I use windows too but with `cygwin` ( which is similar to `git bash` or linux subsystem for windows ) so its not just pure cmd. When I try running `npm run ci` in windows cmd, I get error that the `rm` is unknown command so maybe I can come with some cross environment way of cleaning `dist` folder.

**Comment by tomastrajan** [comment]
I reworked build script a bit and ran it successfully in the windows environment using `cmd` so if you sync your fork you should be able to run `npm run ci` on your local machine.

ps: I use following commands to sync my forks when working on some other repos
1. `git checkout master --force`
2. `git fetch upstream`
3. `git merge upstream/master`
4. `git push`

**Comment by hhubik** [comment]
@tomastrajan - Thanks for the advice.  I just did what you suggested (sync'd my fork using the commands above).  Unfortunately I still get the same `ELIFECYCLE` error from `npm run ci` on my machine` as before.  I use `git bash`.  I wonder if this has something to do with VS Code.  Specifically, with the fact that (I think) it changes line endings from CR to CRLF when it saves a file. I will make a brand new copy of the project and try to run `npm run ci` locally on it without changing it first.

**Comment by hhubik** [comment]
@tomastrajan  CI started to work after I ran `npm run prettier`, which appears to do `prettier --write`.  

In my last commit, I tried to use the proper commit message syntax. I hope that worked.  I also put the `close` tag in the comment footer, unfortunately I typed `#134` instead of `#126` (the correct issue number).  I don't know how to fix that in the existing comment.

Let me know if I need to do anything else on this.

**Comment by tomastrajan** [comment]
Thank you very much for your contribution!

**Pull request merged**
