### PR TITLE
Form inputs

### PR DESCRIPTION
**Pull request by KadarH**
I think that the button save in the examples module ( form ) has to be disabled if the auto save is disabled or while the form is not valid .

```
if( autosave ) => disabled
else while( form not valid ) => disabled
=> enabled
```

The actual use :

`[disabled]="form.get('autosave').value`

My proposition : 

`[disabled]="form.get('autosave').value || !form.valid"`

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hi @KadarH  !

We want to be able to also safe invalid form, it's like work in progress. Maybe not ready yet but we dont want to lose it and be able to continue when we come back.

We only want to prevent SUBMIT of the form if its not valid.

Hope that makes sense!

**Comment by KadarH** [comment]
Hi @tomastrajan 

So if we want to be able to also save invalid form, it is more logical that the inputs are not required.
In my opinion, required restrictions is used to tell the user that he can't save the form until the input is not empty.

Proposition : 

1 - No restrictions ( all input become not required ) => save form 
Or 
2 - The form cannot be saved until the inputs are filled ( unless the autoSave is activated )

What do you think ?
Regards

**Comment by KadarH** [comment]
> Hi @tomastrajan
> 
> So if we want to be able to also save invalid form, it is more logical that the inputs are not required.
> In my opinion, required restrictions is used to tell the user that he can't save the form until the input is not empty.
> 
> **Proposition :**
> 
> * No restrictions ( all input become not required ) => save form
> 
> Or
> 
> * The form cannot be saved until the inputs are filled ( unless the autoSave is activated )
> 
> What do you think ?
> Regards

**Comment by tomastrajan** [comment]
@KadarH maybe we should just rename `Save` button to `Save draft` because i think its a valid use case... I work on something big, it's not yet all valid, I need more data to finish the filling of the form, but I want to continue tomorrow, so I save the draft and continue tomorrow. Once I filled everything and form is valid I can finally submit it for real ?

**Review by jiddisch — APPROVED** [review]

**Pull request closed without merging**
