### PR TITLE
test(settings): added SettingsEffects unit test

### LINKED ISSUE #270: Create unit tests for settings effects
Create tests for `settings.effects.ts` in `settings.effects.spec.ts` file either by following [official ngrx testing guide](https://github.com/ngrx/platform/blob/master/docs/store/testing.md) or feel free to suggest any improvements.

Try to keep tests as independent as possible (eg minimize importing of various modules in setting up tests)

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

### PR DESCRIPTION
**Pull request by hhubik**
closes #270

### CODE REVIEW

**Comment by hhubik** [comment]
Left out one file from the commit.  Will try again.

**Comment by timdeschryver** [comment]
@hhubik you can add a file to your previous commit with

``bash
git add .
git commit --amend

git commit --amend --no-edit
git push --force
```

Just as a fyi :)

**Comment by tomastrajan** [comment]
@timdeschryver thank you for supporting other contributors!

**Comment by hhubik** [comment]
@timdeschryver - Thanks for the suggestion.

**Pull request closed without merging**
