### PR TITLE
Added docker-compose.yml to run the app using docker-compose

### PR DESCRIPTION
**Pull request by kosmas58**
## What:
Added docker-compose.yml to run the app using docker-compose.

### CODE REVIEW

**Comment by tomastrajan** [comment]
@kosmas58 thank you for your contribution, can you please provide more background / links ? I am not very well versed with the docker technology. Thank you!

**Comment by kosmas58** [comment]
@tomastrajan thanks for your reply.  To be honest, the benefits of docker-compose for Angular-Material-Starter are small. The main purpose of `docker-compose` is to orchestrate a series of containers (e.g. a web server with a database server) to generate and start them together.  I've added it because it's usually part of my toolset.

I've made the changes to the `Dockerfile` and `.dockerignore` because `husky` otherwise produces error messages under `docker run` and `docker-compose`.

**Comment by tomastrajan** [comment]
@kosmas58 does this have an impact on people who would just want to run in with most basic docker setup? Do they have to have installed something more in their environment? 

In general we want stuff to work for the most people possible without getting too specific in one direction and as said before don't really know docker that well so that's why I am asking ;)

**Comment by kosmas58** [comment]
@tomastrajan  [Compose](https://docs.docker.com/compose/overview/) is part of the normal docker installation. 

> _Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration._

The only thing you need to use it, is a `docker-compose.yml` file, which I've added.

**Comment by kosmas58** [comment]
@tomastrajan  many thanks for merging it in.

**Pull request merged**
