### PR TITLE
test(settings): add unit tests for settings actions, closes #338

### LINKED ISSUE #338: Create unit tests for settings actions
Create tests for [settings.actions.ts](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/src/app/settings/settings.actions.ts) in `settings.actions.spec.ts` file by **following already existing tests**, the official Angular testing guide or feel free to suggest improvements!

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

Don't forget to reference this issue in the commit message (eg `test(settings): add unit tests for <something>, closes #<issue-number>`)

### PR DESCRIPTION
**Pull request by zetsnotdead**
## What:

Add specs for settings actions

Issue number: #338

### CODE REVIEW

**Comment by zetsnotdead** [comment]
The failing spec is not related to the PR.

**Comment by timdeschryver** [comment]
Yea, the failing spec you're seeing is a known hiccup... 😅

**Comment by erhise** [comment]
> Yea, the failing spec you're seeing is a known hiccup... 😅

If I only had known this earlier :sweat_smile:, I think I spent almost half an hour trying to implement a unit test for effects with store dependency (books.effects.ts), sometimes breaking just this one :weary:
Even though I thought something was unstable I just threw everything in the trash, even though the created test passed.

**Comment by timdeschryver** [comment]
I'm sorry to hear that @erhise.

@tomastrajan would it be OK for you to just skip this test? Once there are "real" tests for the example component it would resolve itself, if not we can take a look at it then.

**Pull request merged**
