### PR TITLE
test(BigInputComponent): created unit test for BigInputComponent

### LINKED ISSUE #271: Create unit tests for big input component
Create unit test for `big-input.component.ts` in `big-input.component.spec.ts` that covers its functionality.

Please follow testing pattern introduced in [big-input-action.component.spec.ts](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/src/app/shared/big-input/big-input-action.component.spec.ts) or please suggest improvements in the comments.

Feel free to check out [Contributors Guide](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/CONTRIBUTING.md) for useful tips and hints that help you get started.

### PR DESCRIPTION
**Pull request by hhubik**
fixes #271

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hi @hhubik !

Thank you for your PR! Please, can you put fixes into the commit message so that it looks like `test(BigInputComponent): created unit test for BigInputComponent, fixes #271` and GitHub can auto close issue once merged.

Also please fix prettier issues in [Travis CI](https://travis-ci.org/tomastrajan/angular-ngrx-material-starter/builds/404155531#L529) build by running `npm run prettier` and commiting and rebasing (`git rebase -i HEAD~1` and then use `f` flag to squash extra commit) changes so that we end up with the single commit, thank you!

**Comment by hhubik** [comment]
@tomastrajan I got the `prettier` issue resolved in my local work branch `big-input-test`.  However, I am struggling a bit with the git part.  Specifically, squashing everything into one commit.  What did you mean by `f flag`?  Sorry, I am just starting with git.

**Comment by hhubik** [comment]
I will open a new PR using a new branch that has only the commit we want with correct comment syntax.

**Comment by tomastrajan** [comment]
@hhubik ok that will work too! And for that git thing, if you have a branch with multiple commits, you can squash them together so you will end up with the single commit. It is possible to do that on the command line with `git rebase -i HEAD~2`. The `-i` means interactive and `HEAD~2` mens last 2 commits so you can do it also for more if necessary. This opens a interactive command line editor (usually vi or notepad based on the OS) which contains those commits all prepended by a flag (by default it is `pick`) and you can change the flag to `f` for the commits you want to squash so their content is preserved by commit message is removed from the history.

rebase

**Pull request closed without merging**
