### PR TITLE
feat(i18n): Reworked translations using BabelEdit 'https://www.codean…

### PR DESCRIPTION
**Pull request by kosmas58**
## What:

Added missing translations. I used [BabelEdit](https://www.codeandweb.com/babeledit) to do it. Therefore I  had to change some definitions, because they lead to errors in BabelEdit.

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hi @kosmas58 ! Thank you for your contribution, this looks pretty good. 

Just a quick question, are you in some way affiliated with the BabelEdit? I mean it seems like a nice tool but I have never ever before seen somebody putting name and url of a tool in the commit message :)

**Comment by kosmas58** [comment]
Hi @tomastrajan, my relation to BabelEdit is, that I'm a paying customer and user of this product. I've been using it in another project, that I'm [contributing to](https://github.com/LINCnil/pia).

**Comment by timdeschryver** [comment]
Seems like a great tool!

**Comment by tomastrajan** [comment]
@kosmas58 thank you for your explanation and again for the great contribution!

**Comment by kosmas58** [comment]
Hi @tomastrajan, thanks for your support and thanks for your project. It helps a lot, when starting an angular material project,.

**Pull request merged**
