### PR TITLE
feat(tool): change to eslint In favor of tslint deprecation

### PR DESCRIPTION
**Pull request by SiddharthSh**
## What:
eslint has been introduced as part of tslint deprecation.

* code has been slightly modified to support the linting since eslint is more strict when converted.

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hey @SiddharthSh !

Thank you very much for your contribution!

Don't we need to remove tslint.json files and the dependency ?

**Comment by SiddharthSh** [comment]
Hey @tomastrajan, good catch, have pushed latest by removing the tslint and incorporating the component and directive selector to the eslint rules. Also, RTL is being ignored in the codebase so I let it remain as is.
We cant remove dependency for tslint since the eslint plugin depends on it. :)

**Comment by SiddharthSh** [comment]
Not sure why the Travis CI build is failing, running on my system seems fine :(

**Comment by tomastrajan** [comment]
@SiddharthSh yeah really strange as initially your PR built just fine, also in `[rtl]` you just added comment, hard to imagine what's going wrong...

**Comment by tomastrajan** [comment]
@SiddharthSh btw one more thing, maybe it would make sense to add eslint entry here https://tomastrajan.github.io/angular-ngrx-material-starter#/feature-list to highlight that this is already future proof ;)

**Comment by SiddharthSh** [comment]
For future-readiness, I think yea better to showcase, so pushed another commit with the latest changes @tomastrajan

**Comment by tomastrajan** [comment]
@SiddharthSh merged and released, thank you for your contribution!

**Pull request merged**
